"""NIROS Human Understanding Engine."""

from niros.intake_readiness import (
    DEFAULT_MINIMUM_REQUIRED_SCORE,
    IntakeReadinessReport,
    build_readiness_report_from_session,
    evaluate_intake_readiness,
)
from niros.information_gain import (
    InformationGainCandidate,
    calculate_information_gain_scores,
    select_highest_information_gain,
)
from niros.intake_session_state import (
    DEFAULT_INTAKE_SESSION_ID,
    IntakeSessionState,
    IntakeTurn,
    add_user_turn,
    build_intake_transcript,
    build_person_fit_profile_from_intake,
    create_intake_session,
)
from niros.clarification_selector import (
    QUESTION_PRIORITY_ORDER,
    QUESTION_STATUS_PENDING,
    ClarificationQuestion,
    select_adaptive_question,
    select_next_clarification_question,
)
from niros.intake_coverage import (
    REQUIRED_COVERAGE_DIMENSIONS,
    IntakeCoverageReport,
    IntakeCoverageState,
    evaluate_intake_coverage,
    update_coverage_from_signals,
)
from niros.evidence import (
    EvidenceItem,
    EvidenceSource,
    EvidenceType,
    statement_to_evidence,
    statements_to_evidence,
)
from niros.hypotheses import Hypothesis, HypothesisGenerator, HypothesisType, generate_hypotheses
from niros.interview_engine import (
    BlueprintPhase,
    InterviewDecision,
    InterviewDecisionEngine,
)
from niros.knowledge import KnowledgePattern, PatternLoader, PatternRelationship, PatternRelationType
from niros.models import (
    IcaroLanguage,
    InterviewPhase,
    InterviewState,
    SupportedLanguage,
)
from niros.pattern_person_fit_contracts import (
    NOT_RECOMMENDED,
    RECOMMENDED,
    USE_WITH_CAUTION,
    PatternFitReport,
    PatternFitScore,
    PersonFitProfile,
)
from niros.pattern_person_fit_ranking import rank_patterns_for_profile
from niros.pattern_person_fit_report import build_pattern_fit_report
from niros.pattern_person_fit_scoring import score_pattern_fit
from niros.patterns import (
    PatternTag,
    PatternTagger,
    pattern_tag_evidence,
    pattern_tag_evidence_items,
)
from niros.questions import (
    FollowUpQuestionSelector,
    GraphQuestionSuggester,
    QuestionSuggestion,
    select_follow_up_questions,
    suggest_next_questions,
)
from niros.state_machine import InvalidTransitionError, advance, initial_state
from niros.statements import (
    Statement,
    UnsupportedModalityError,
    split_transcript_to_statements,
)
from niros.strategy_candidate_builder import (
    DEFAULT_STRATEGY_ID,
    DRAFT_STRATEGY_STATUS,
    StrategyCandidate,
    build_strategy_candidate,
)
from niros.strategy_explanation import (
    StrategyExplanation,
    StrategyExplanationItem,
    build_strategy_explanation,
)
from niros.patient_repository import (
    PATIENT_STATUS_ACTIVE,
    PatientRecord,
    PatientRepository,
    SessionRecord,
    create_patient,
    create_session,
    get_patient,
    list_sessions_for_patient,
    load_repository,
    save_repository,
)
from niros.source_import import (
    DEFAULT_IMPORT_STATUS,
    SourceImportManifest,
    build_import_manifest,
    validate_import_manifest,
)
from niros.txt_source_importer import (
    import_txt_as_raw_corpus,
    read_txt_source,
    split_text_into_segments,
)
from niros.semantic_extraction_prompt import (
    REQUIRED_EXTRACTION_FIELDS,
    build_semantic_extraction_prompt,
)
from niros.knowledge_workspace import (
    DEFAULT_KNOWLEDGE_ROOT,
    KnowledgeWorkspacePaths,
    build_knowledge_workspace_paths,
    ensure_knowledge_workspace,
    knowledge_artifact_path,
)
from niros.openai_extraction_adapter import (
    DEFAULT_ADAPTER_VERSION,
    DEFAULT_EXTRACTION_PROMPT_VERSION,
    ExtractionRequest,
    ExtractionResponse,
    build_extraction_request,
    build_extraction_response,
    validate_extraction_response,
)
from niros.openai_semantic_extraction_adapter import (
    DEFAULT_EXTRACTOR_NAME,
    DEFAULT_OPENAI_MODEL,
    OpenAIChatCompletionClient,
    OpenAISemanticExtractionAdapter,
    SemanticExtractionAdapterError,
    SemanticExtractionApiError,
    SemanticExtractionEmptyResponseError,
    SemanticExtractionInvalidJsonError,
    SemanticExtractionMissingApiKeyError,
    SemanticExtractionValidationError,
    parse_therapeutic_extraction_json,
    resolve_openai_model,
)
from niros.source_registry import (
    DEFAULT_PROCESSING_STATUS,
    KnowledgeSourceRecord,
    KnowledgeSourceRegistry,
    build_source_registry,
    get_source_record,
    list_sources_by_family,
    list_sources_by_status,
    mark_source_status,
    validate_source_record,
)
from niros.human_review_workflow import (
    REVIEW_STATUS_APPROVED,
    REVIEW_STATUS_CHANGES_REQUESTED,
    REVIEW_STATUS_PENDING,
    REVIEW_STATUS_REJECTED,
    HumanReviewError,
    HumanReviewNotFoundError,
    HumanReviewRecord,
    HumanReviewStateError,
    HumanReviewValidationError,
    HumanReviewWorkflow,
    build_review_id,
    deserialize_extraction,
    deserialize_human_review_record,
    effective_extraction,
    serialize_extraction,
    serialize_human_review_record,
    validate_human_review_record,
)
from niros.extraction_pipeline import (
    ExtractionPipelineResult,
    build_extraction_pipeline,
    merge_pipeline_results,
)
from niros.therapeutic_extraction import (
    TherapeuticFunctionExtraction,
    build_ctpc_pattern_from_extraction,
    build_extraction_id,
    validate_extraction,
)
from niros.raw_source import (
    RawSource,
    RawSourceCorpus,
    RawSourceSegment,
    build_raw_source_corpus,
    validate_raw_segment,
    validate_raw_source,
)
from niros.raw_corpus_io import (
    deserialize_raw_corpus,
    deserialize_raw_segment,
    deserialize_raw_source,
    load_raw_corpus,
    save_raw_corpus,
    serialize_raw_corpus,
    serialize_raw_segment,
    serialize_raw_source,
)
from niros.ctpc import (
    CTPCLibrary,
    CanonicalTherapeuticPattern,
    build_ctpc_library,
    find_patterns_by_function,
    find_patterns_for_functions,
    get_ctpc_pattern,
    validate_ctpc_pattern,
)
from niros.therapeutic_vocal_engine import (
    DEFAULT_ICARO_ID,
    IcaroProfile,
    build_icaro_profile_from_strategy,
)
from niros.transcript import InputModality, Transcript
from niros.voice_transcript import (
    DEFAULT_CONFIDENCE,
    DEFAULT_LANGUAGE,
    DEFAULT_SESSION_ID,
    DEFAULT_SOURCE,
    TRANSCRIPT_STATUS_TRANSCRIBED,
    VoiceInput as VoiceTranscriptInput,
    VoiceTranscript,
    create_transcript_from_text,
)
from niros.whisper_adapter import (
    DEFAULT_DEVICE,
    DEFAULT_MODEL_NAME,
    DEFAULT_PROVIDER,
    WhisperAdapterConfig,
    WhisperTranscriptionResult,
    build_whisper_transcription_result,
    transcribe_audio_mock,
)

__all__ = [
    "BlueprintPhase",
    "CanonicalTherapeuticPattern",
    "ClarificationQuestion",
    "CTPCLibrary",
    "DEFAULT_ADAPTER_VERSION",
    "DEFAULT_EXTRACTION_PROMPT_VERSION",
    "DEFAULT_ICARO_ID",
    "DEFAULT_PROCESSING_STATUS",
    "DEFAULT_CONFIDENCE",
    "DEFAULT_INTAKE_SESSION_ID",
    "DEFAULT_IMPORT_STATUS",
    "DEFAULT_EXTRACTOR_NAME",
    "DEFAULT_KNOWLEDGE_ROOT",
    "DEFAULT_LANGUAGE",
    "DEFAULT_OPENAI_MODEL",
    "DEFAULT_PROVIDER",
    "DEFAULT_SESSION_ID",
    "DEFAULT_SOURCE",
    "DEFAULT_STRATEGY_ID",
    "DRAFT_STRATEGY_STATUS",
    "EvidenceItem",
    "EvidenceSource",
    "EvidenceType",
    "ExtractionPipelineResult",
    "ExtractionRequest",
    "ExtractionResponse",
    "FollowUpQuestionSelector",
    "GraphQuestionSuggester",
    "Hypothesis",
    "HypothesisGenerator",
    "HypothesisType",
    "HumanReviewError",
    "HumanReviewNotFoundError",
    "HumanReviewRecord",
    "HumanReviewStateError",
    "HumanReviewValidationError",
    "HumanReviewWorkflow",
    "IcaroProfile",
    "IcaroLanguage",
    "KnowledgePattern",
    "KnowledgeSourceRecord",
    "KnowledgeSourceRegistry",
    "KnowledgeWorkspacePaths",
    "InputModality",
    "InformationGainCandidate",
    "IntakeCoverageReport",
    "IntakeCoverageState",
    "IntakeReadinessReport",
    "IntakeSessionState",
    "IntakeTurn",
    "InterviewDecision",
    "InterviewDecisionEngine",
    "InterviewPhase",
    "InterviewState",
    "InvalidTransitionError",
    "NOT_RECOMMENDED",
    "OpenAIChatCompletionClient",
    "OpenAISemanticExtractionAdapter",
    "PATIENT_STATUS_ACTIVE",
    "PatternFitReport",
    "PatternFitScore",
    "PersonFitProfile",
    "PatientRecord",
    "PatientRepository",
    "PatternTag",
    "PatternTagger",
    "PatternLoader",
    "QUESTION_PRIORITY_ORDER",
    "QUESTION_STATUS_PENDING",
    "PatternRelationship",
    "PatternRelationType",
    "QuestionSuggestion",
    "SemanticExtractionAdapterError",
    "SemanticExtractionApiError",
    "SemanticExtractionEmptyResponseError",
    "SemanticExtractionInvalidJsonError",
    "SemanticExtractionMissingApiKeyError",
    "SemanticExtractionValidationError",
    "RawSource",
    "RawSourceCorpus",
    "RawSourceSegment",
    "RECOMMENDED",
    "REQUIRED_COVERAGE_DIMENSIONS",
    "REQUIRED_EXTRACTION_FIELDS",
    "REVIEW_STATUS_APPROVED",
    "REVIEW_STATUS_CHANGES_REQUESTED",
    "REVIEW_STATUS_PENDING",
    "REVIEW_STATUS_REJECTED",
    "Statement",
    "SessionRecord",
    "SourceImportManifest",
    "StrategyCandidate",
    "StrategyExplanation",
    "StrategyExplanationItem",
    "SupportedLanguage",
    "TherapeuticFunctionExtraction",
    "TRANSCRIPT_STATUS_TRANSCRIBED",
    "Transcript",
    "UnsupportedModalityError",
    "USE_WITH_CAUTION",
    "VoiceTranscript",
    "VoiceTranscriptInput",
    "WhisperAdapterConfig",
    "WhisperTranscriptionResult",
    "advance",
    "add_user_turn",
    "build_ctpc_library",
    "build_ctpc_pattern_from_extraction",
    "build_extraction_id",
    "build_extraction_pipeline",
    "build_extraction_request",
    "build_extraction_response",
    "build_icaro_profile_from_strategy",
    "build_intake_transcript",
    "build_knowledge_workspace_paths",
    "build_pattern_fit_report",
    "build_person_fit_profile_from_intake",
    "build_review_id",
    "build_raw_source_corpus",
    "build_readiness_report_from_session",
    "build_semantic_extraction_prompt",
    "build_import_manifest",
    "build_source_registry",
    "import_txt_as_raw_corpus",
    "build_strategy_candidate",
    "build_strategy_explanation",
    "build_whisper_transcription_result",
    "calculate_information_gain_scores",
    "create_intake_session",
    "create_patient",
    "create_session",
    "deserialize_human_review_record",
    "deserialize_raw_corpus",
    "deserialize_raw_segment",
    "deserialize_raw_source",
    "ensure_knowledge_workspace",
    "effective_extraction",
    "evaluate_intake_coverage",
    "evaluate_intake_readiness",
    "find_patterns_by_function",
    "find_patterns_for_functions",
    "generate_hypotheses",
    "get_ctpc_pattern",
    "get_patient",
    "get_source_record",
    "initial_state",
    "knowledge_artifact_path",
    "list_sessions_for_patient",
    "list_sources_by_family",
    "list_sources_by_status",
    "load_raw_corpus",
    "load_repository",
    "mark_source_status",
    "merge_pipeline_results",
    "parse_therapeutic_extraction_json",
    "pattern_tag_evidence",
    "pattern_tag_evidence_items",
    "rank_patterns_for_profile",
    "read_txt_source",
    "resolve_openai_model",
    "save_raw_corpus",
    "save_repository",
    "split_text_into_segments",
    "select_adaptive_question",
    "select_follow_up_questions",
    "select_highest_information_gain",
    "serialize_raw_corpus",
    "serialize_extraction",
    "serialize_human_review_record",
    "serialize_raw_segment",
    "serialize_raw_source",
    "score_pattern_fit",
    "split_transcript_to_statements",
    "suggest_next_questions",
    "statement_to_evidence",
    "statements_to_evidence",
    "transcribe_audio_mock",
    "update_coverage_from_signals",
    "validate_ctpc_pattern",
    "validate_import_manifest",
    "validate_human_review_record",
    "validate_extraction",
    "validate_extraction_response",
    "validate_source_record",
    "validate_raw_segment",
    "validate_raw_source",
]
