from __future__ import annotations

from dataclasses import dataclass

CORE_PSYCHOLOGICAL_DOMAIN_IDS: tuple[str, ...] = (
    "self_domain",
    "emotion_regulation_domain",
    "cognitive_patterns_domain",
    "relationships_domain",
    "values_identity_domain",
    "emotional_flexibility_domain",
)

CORE_DOMAIN_IDS: tuple[str, ...] = (
    "low_mood_depression_signals",
    "anxiety_fear_panic",
    "trauma_stress_signals",
    "grief_loss_bereavement",
    "existential_distress_meaning",
    "ocd_rumination_intrusive_thoughts",
    "alcohol_use_patterns",
    "substance_use_patterns",
    "behavioral_addictions",
    "shame_guilt_self_worth",
    "attachment_relationships_trust",
    "emotional_regulation",
    "chronic_stress_burnout",
    "sleep_nightmares",
    "body_somatic_anxiety",
    "chronic_pain_fibromyalgia_fatigue",
    "speech_stuttering_expression",
    "spirituality_meaning_openness_resistance",
    "psychedelic_session_concerns",
    "integration_goals",
) + CORE_PSYCHOLOGICAL_DOMAIN_IDS

CORE_PSYCHOLOGICAL_DIMENSIONS: dict[str, tuple[str, ...]] = {
    "self_domain": (
        "self_worth",
        "shame",
        "self_compassion",
        "self_criticism",
        "agency",
        "belonging",
        "identity",
    ),
    "emotion_regulation_domain": (
        "emotional_suppression",
        "emotional_overwhelm",
        "emotional_avoidance",
        "emotional_awareness",
        "emotional_reactivity",
        "emotion_recovery",
    ),
    "cognitive_patterns_domain": (
        "rumination",
        "catastrophizing",
        "black_and_white_thinking",
        "overgeneralization",
        "hopelessness",
        "mental_overcontrol",
    ),
    "relationships_domain": (
        "attachment_anxiety",
        "attachment_avoidance",
        "trust",
        "intimacy",
        "abandonment",
        "boundaries",
    ),
    "values_identity_domain": (
        "identity_clarity",
        "values_clarity",
        "life_direction",
        "inner_conflict",
        "authenticity",
        "role_confusion",
    ),
    "emotional_flexibility_domain": (
        "psychological_flexibility",
        "acceptance",
        "experiential_avoidance",
        "openness_to_experience",
        "adaptive_response_capacity",
    ),
}

VALID_FINGERPRINT_DIMENSIONS: frozenset[str] = frozenset(
    {
        "presenting_problem",
        "patterns",
        "semantic_facts",
        "big_five",
        "intervention_strategy",
        *(
            dimension
            for dimensions in CORE_PSYCHOLOGICAL_DIMENSIONS.values()
            for dimension in dimensions
        ),
    }
)

SUGGESTED_ASSESSMENT_TOOLS: frozenset[str] = frozenset(
    {
        "PHQ-9",
        "GAD-7",
        "PCL-5",
        "AUDIT",
        "DAST-10",
        "ISI",
        "PSQI",
        "FIQR",
        "PCS",
        "BFI-2",
        "IPIP",
        "DERS",
        "AAQ-II",
        "ECR-R",
        "MLQ",
        "SCS",
        "PTQ",
        "IVC",
    }
)

FORBIDDEN_DIAGNOSTIC_PHRASES: tuple[str, ...] = (
    " diagnosis",
    "diagnose ",
    "diagnosed ",
    "diagnosing ",
    "disorder",
    "clinical depression",
    "major depressive",
    "generalized anxiety disorder",
    "post-traumatic stress disorder",
    "you have ",
    "patient has ",
    " cures ",
    " cure ",
    "treats ",
    "treatment for ",
    "psilocybin cures",
    "medication for ",
)


@dataclass(frozen=True)
class AssessmentDomain:
    domain_id: str
    title: str
    purpose: str
    pattern_ids: tuple[str, ...]
    semantic_fact_categories: tuple[str, ...]
    suggested_assessment_tools: tuple[str, ...]
    fingerprint_dimensions: tuple[str, ...]
    priority: int


def _domain(
    domain_id: str,
    title: str,
    purpose: str,
    pattern_ids: tuple[str, ...],
    semantic_fact_categories: tuple[str, ...],
    suggested_assessment_tools: tuple[str, ...],
    fingerprint_dimensions: tuple[str, ...],
    priority: int,
) -> AssessmentDomain:
    return AssessmentDomain(
        domain_id=domain_id,
        title=title,
        purpose=purpose,
        pattern_ids=pattern_ids,
        semantic_fact_categories=semantic_fact_categories,
        suggested_assessment_tools=suggested_assessment_tools,
        fingerprint_dimensions=fingerprint_dimensions,
        priority=priority,
    )


def build_assessment_domain_map() -> dict[str, AssessmentDomain]:
    domains = (
        _domain(
            "low_mood_depression_signals",
            "Low Mood and Depression-Like Signals",
            "Understand self-reported low mood, anhedonia, heaviness, and hopelessness as observed intake signals — not diagnostic labels.",
            (
                "low_mood_signal",
                "depressed_mood_signal",
                "anhedonia_signal",
                "hopelessness_signal",
                "emotional_heaviness",
            ),
            ("emotion", "self"),
            ("PHQ-9",),
            ("presenting_problem", "patterns", "semantic_facts", "intervention_strategy"),
            9,
        ),
        _domain(
            "anxiety_fear_panic",
            "Anxiety, Fear, and Panic Signals",
            "Understand self-reported fear, panic, and anticipatory anxiety as observed intake signals for session planning.",
            (
                "generalized_fear",
                "panic_reactivity",
                "anxiety_reactivity",
                "fear_of_losing_control",
                "fear_of_death",
                "anticipation_anxiety",
                "emotional_distress_signal",
            ),
            ("emotion", "safety"),
            ("GAD-7",),
            ("presenting_problem", "patterns", "semantic_facts", "intervention_strategy"),
            9,
        ),
        _domain(
            "trauma_stress_signals",
            "Trauma and Stress Signals",
            "Understand self-reported trauma-related stress, hypervigilance, intrusion, and avoidance as observed intake signals.",
            (
                "hypervigilance",
                "intrusive_memories",
                "avoidance_of_triggers",
                "emotional_numbing",
                "dissociation_signal",
                "startle_sensitivity",
                "shame_after_vulnerability",
            ),
            ("trauma", "emotion", "safety"),
            ("PCL-5",),
            ("presenting_problem", "patterns", "semantic_facts", "intervention_strategy"),
            9,
        ),
        _domain(
            "grief_loss_bereavement",
            "Grief, Loss, and Bereavement",
            "Understand self-reported grief, bereavement context, and loss-related distress as observed intake signals.",
            (
                "grief_signal",
                "bereavement_context",
                "loss_related_distress",
                "relationship_breakup_context",
                "attachment_loss_signal",
                "separation_distress",
                "abandonment_wound_signal",
            ),
            ("life_event", "emotion", "relationship"),
            (),
            ("presenting_problem", "patterns", "semantic_facts", "intervention_strategy"),
            8,
        ),
        _domain(
            "existential_distress_meaning",
            "Existential Distress and Meaning",
            "Understand self-reported meaning loss, existential fear, and identity uncertainty as observed intake signals.",
            (
                "loss_of_meaning",
                "hopelessness_signal",
                "existential_fear",
                "identity_confusion",
                "identity_uncertainty",
                "search_for_self_understanding",
                "life_transition_distress",
            ),
            ("meaning", "self", "emotion"),
            ("MLQ", "AAQ-II"),
            ("presenting_problem", "patterns", "semantic_facts", "big_five", "intervention_strategy"),
            8,
        ),
        _domain(
            "ocd_rumination_intrusive_thoughts",
            "Rumination and Intrusive Thought Loops",
            "Understand self-reported rumination, obsessive loops, and mental overcontrol as observed intake signals.",
            (
                "rumination",
                "obsessive_thinking_loop",
                "mental_overcontrol",
                "inability_to_let_go",
                "inner_conflict",
            ),
            ("emotion", "self"),
            ("AAQ-II",),
            ("patterns", "semantic_facts", "intervention_strategy"),
            7,
        ),
        _domain(
            "alcohol_use_patterns",
            "Alcohol Use Patterns",
            "Understand self-reported alcohol use context and related distress signals disclosed during intake — not eligibility claims.",
            (
                "emotional_avoidance",
                "guilt_burden",
                "chronic_stress_signal",
            ),
            ("emotion", "self", "agency"),
            ("AUDIT",),
            ("presenting_problem", "semantic_facts", "patterns", "intervention_strategy"),
            8,
        ),
        _domain(
            "substance_use_patterns",
            "Substance Use Patterns",
            "Understand self-reported substance use context and related coping signals disclosed during intake — not eligibility claims.",
            (
                "substance_use_pattern",
                "drug_use_concern",
                "addiction_concern_signal",
                "compulsive_use_signal",
                "loss_of_control_over_use",
                "substance_preoccupation",
                "recovery_goal_signal",
            ),
            ("substance", "emotion", "agency"),
            ("DAST-10",),
            ("presenting_problem", "semantic_facts", "patterns", "intervention_strategy"),
            8,
        ),
        _domain(
            "behavioral_addictions",
            "Behavioral Addiction-Like Patterns",
            "Understand self-reported compulsive or repetitive behavioral patterns as observed intake signals.",
            (
                "compulsive_use_signal",
                "substance_preoccupation",
                "loss_of_control_over_use",
                "rumination",
                "obsessive_thinking_loop",
            ),
            ("emotion", "self", "agency"),
            (),
            ("presenting_problem", "patterns", "semantic_facts", "intervention_strategy"),
            6,
        ),
        _domain(
            "shame_guilt_self_worth",
            "Shame, Guilt, and Self-Worth",
            "Understand self-reported shame sensitivity, guilt burden, and self-worth instability as observed intake signals.",
            (
                "shame_sensitivity",
                "harsh_self_criticism",
                "self_worth_instability",
                "guilt_burden",
                "unworthiness_signal",
                "social_disconnection_signal",
                "rejection_sensitivity",
                "shame_after_vulnerability",
            ),
            ("self", "emotion"),
            ("BFI-2", "IPIP"),
            ("presenting_problem", "patterns", "semantic_facts", "big_five", "intervention_strategy"),
            8,
        ),
        _domain(
            "attachment_relationships_trust",
            "Attachment, Relationships, and Trust",
            "Understand self-reported attachment anxiety, trust difficulty, and relationship strain as observed intake signals.",
            (
                "attachment_anxiety",
                "trust_difficulty",
                "fear_of_rejection",
                "boundary_difficulty",
                "people_pleasing",
                "conflict_avoidance",
                "trust_in_facilitator_difficulty",
            ),
            ("relationship", "emotion"),
            ("ECR-R", "BFI-2"),
            ("presenting_problem", "patterns", "semantic_facts", "big_five", "intervention_strategy"),
            8,
        ),
        _domain(
            "emotional_regulation",
            "Emotional Regulation",
            "Understand self-reported suppression, avoidance, overwhelm, and awareness gaps as observed regulation signals.",
            (
                "emotional_suppression",
                "emotional_avoidance",
                "emotional_overwhelm",
                "emotional_distress_signal",
                "emotional_awareness",
                "emotional_numbing",
                "inability_to_let_go",
            ),
            ("emotion", "self"),
            ("DERS",),
            ("patterns", "semantic_facts", "big_five", "intervention_strategy"),
            9,
        ),
        _domain(
            "chronic_stress_burnout",
            "Chronic Stress and Burnout",
            "Understand self-reported chronic stress, exhaustion, and overload as observed intake signals.",
            (
                "chronic_stress_signal",
                "fatigue_burden",
                "emotional_overwhelm",
                "frustration_with_medical_system",
                "chronic_tension",
            ),
            ("emotion", "body", "self"),
            ("GAD-7",),
            ("presenting_problem", "patterns", "semantic_facts", "intervention_strategy"),
            8,
        ),
        _domain(
            "sleep_nightmares",
            "Sleep and Nightmares",
            "Understand self-reported sleep disruption and nightmare disturbance as observed intake signals.",
            (
                "sleep_disruption",
                "nightmare_disturbance",
            ),
            ("sleep", "emotion", "body"),
            ("ISI", "PSQI"),
            ("presenting_problem", "patterns", "semantic_facts", "intervention_strategy"),
            8,
        ),
        _domain(
            "body_somatic_anxiety",
            "Body and Somatic Anxiety",
            "Understand self-reported body sensitivity, somatic anxiety, and body-trust difficulty as observed intake signals.",
            (
                "somatic_anxiety",
                "fear_of_body_sensations",
                "body_sensitivity",
                "body_trust_difficulty",
                "startle_sensitivity",
                "pain_fear_cycle",
            ),
            ("body", "emotion"),
            ("PCS",),
            ("patterns", "semantic_facts", "intervention_strategy"),
            8,
        ),
        _domain(
            "chronic_pain_fibromyalgia_fatigue",
            "Chronic Pain, Fibromyalgia, and Fatigue",
            "Understand self-reported pain burden, fibromyalgia-like signals, and fatigue as observed intake signals.",
            (
                "chronic_pain_burden",
                "fibromyalgia_signal",
                "fatigue_burden",
                "activity_avoidance_due_to_pain",
                "symptom_unpredictability",
                "frustration_with_medical_system",
            ),
            ("body", "emotion"),
            ("FIQR", "PCS"),
            ("presenting_problem", "patterns", "semantic_facts", "intervention_strategy"),
            8,
        ),
        _domain(
            "speech_stuttering_expression",
            "Speech, Stuttering, and Expression",
            "Understand self-reported stuttering, speech anxiety, and expression blocks as observed intake signals.",
            (
                "stuttering_signal",
                "speech_anxiety",
                "fear_of_speaking",
                "communication_avoidance",
                "shame_about_speech",
                "self_expression_block",
                "loss_of_control_in_speech",
                "social_visibility_fear",
            ),
            ("speech", "emotion", "relationship"),
            (),
            ("presenting_problem", "patterns", "semantic_facts", "intervention_strategy"),
            7,
        ),
        _domain(
            "spirituality_meaning_openness_resistance",
            "Spirituality, Meaning, Openness, and Resistance",
            "Understand self-reported spiritual openness, resistance, and meaning-seeking as observed intake signals.",
            (
                "spiritual_openness",
                "spiritual_resistance",
                "meaning_seeking",
                "mystical_expectation",
                "desire_for_change",
                "search_for_self_understanding",
            ),
            ("meaning", "session", "self"),
            ("MLQ", "AAQ-II", "BFI-2", "IPIP"),
            ("patterns", "semantic_facts", "big_five", "intervention_strategy"),
            7,
        ),
        _domain(
            "psychedelic_session_concerns",
            "Psychedelic Session Concerns",
            "Understand self-reported session fears, surrender difficulty, and facilitator trust as observed intake signals — not treatment claims.",
            (
                "fear_of_bad_trip",
                "psychedelic_anxiety",
                "surrender_difficulty",
                "control_resistance",
                "fear_of_body_sensations",
                "fear_of_going_crazy",
                "fear_of_losing_control",
                "safety_concern_signal",
                "trust_in_facilitator_difficulty",
            ),
            ("session", "safety", "psychedelic", "emotion"),
            (),
            ("presenting_problem", "patterns", "semantic_facts", "intervention_strategy"),
            10,
        ),
        _domain(
            "integration_goals",
            "Integration Goals",
            "Understand self-reported integration needs, desired change, and meaning goals as observed post-session planning signals.",
            (
                "integration_need",
                "meaning_seeking",
                "desire_for_change",
                "search_for_self_understanding",
            ),
            ("meaning", "self", "agency"),
            ("MLQ", "AAQ-II"),
            ("presenting_problem", "patterns", "semantic_facts", "intervention_strategy"),
            9,
        ),
        _domain(
            "self_domain",
            "Self Structure",
            "Understand self-reported self-worth, shame, self-criticism, agency, belonging, and identity themes as observed psychological structure — not diagnostic labels.",
            (
                "unworthiness_signal",
                "self_worth_instability",
                "shame_sensitivity",
                "shame_after_vulnerability",
                "guilt_burden",
                "harsh_self_criticism",
                "low_self_efficacy",
                "desire_for_change",
                "recovery_goal_signal",
                "social_disconnection_signal",
                "rejection_sensitivity",
                "identity_confusion",
                "identity_uncertainty",
                "search_for_self_understanding",
            ),
            ("self", "emotion", "social", "agency"),
            ("SCS", "BFI-2", "IPIP"),
            CORE_PSYCHOLOGICAL_DIMENSIONS["self_domain"],
            8,
        ),
        _domain(
            "emotion_regulation_domain",
            "Emotion Regulation Structure",
            "Understand self-reported suppression, overwhelm, avoidance, awareness, reactivity, and recovery patterns as observed regulation structure.",
            (
                "emotional_suppression",
                "emotional_overwhelm",
                "emotional_avoidance",
                "emotional_awareness",
                "anxiety_reactivity",
                "panic_reactivity",
                "emotional_distress_signal",
                "inability_to_let_go",
                "emotional_numbing",
            ),
            ("emotion", "self"),
            ("DERS",),
            CORE_PSYCHOLOGICAL_DIMENSIONS["emotion_regulation_domain"],
            8,
        ),
        _domain(
            "cognitive_patterns_domain",
            "Cognitive Pattern Structure",
            "Understand self-reported rumination, catastrophizing, rigid thinking, and hopelessness loops as observed cognitive structure.",
            (
                "rumination",
                "obsessive_thinking_loop",
                "anticipation_anxiety",
                "generalized_fear",
                "fear_of_death",
                "perfectionism",
                "mental_overcontrol",
                "hopelessness_signal",
                "inner_conflict",
            ),
            ("emotion", "self", "meaning"),
            ("PTQ", "AAQ-II"),
            CORE_PSYCHOLOGICAL_DIMENSIONS["cognitive_patterns_domain"],
            8,
        ),
        _domain(
            "relationships_domain",
            "Relationship Structure",
            "Understand self-reported attachment, trust, intimacy, abandonment, and boundary themes as observed relationship structure.",
            (
                "attachment_anxiety",
                "conflict_avoidance",
                "communication_avoidance",
                "social_withdrawal",
                "trust_difficulty",
                "trust_in_facilitator_difficulty",
                "fear_of_rejection",
                "attachment_loss_signal",
                "abandonment_wound_signal",
                "boundary_difficulty",
                "people_pleasing",
            ),
            ("relationship", "emotion", "social"),
            ("ECR-R", "BFI-2"),
            CORE_PSYCHOLOGICAL_DIMENSIONS["relationships_domain"],
            8,
        ),
        _domain(
            "values_identity_domain",
            "Values and Identity Structure",
            "Understand self-reported identity clarity, values clarity, life direction, and inner conflict as observed meaning structure.",
            (
                "identity_confusion",
                "identity_uncertainty",
                "meaning_seeking",
                "loss_of_meaning",
                "life_transition_distress",
                "desire_for_change",
                "inner_conflict",
                "search_for_self_understanding",
            ),
            ("meaning", "self", "agency"),
            ("MLQ", "IVC"),
            CORE_PSYCHOLOGICAL_DIMENSIONS["values_identity_domain"],
            8,
        ),
        _domain(
            "emotional_flexibility_domain",
            "Emotional Flexibility Structure",
            "Understand self-reported acceptance, experiential avoidance, openness, and adaptive response capacity as observed flexibility structure.",
            (
                "control_resistance",
                "surrender_difficulty",
                "emotional_avoidance",
                "avoidance_of_triggers",
                "spiritual_openness",
                "mystical_expectation",
                "desire_for_change",
                "recovery_goal_signal",
            ),
            ("emotion", "self", "agency", "meaning"),
            ("AAQ-II",),
            CORE_PSYCHOLOGICAL_DIMENSIONS["emotional_flexibility_domain"],
            8,
        ),
    )

    return {domain.domain_id: domain for domain in domains}


def get_assessment_domain(domain_id: str) -> AssessmentDomain | None:
    return build_assessment_domain_map().get(domain_id)


def all_assessment_domains() -> tuple[AssessmentDomain, ...]:
    domain_map = build_assessment_domain_map()
    return tuple(domain_map[domain_id] for domain_id in CORE_DOMAIN_IDS)


def domain_map_contains_diagnostic_language(domain: AssessmentDomain) -> bool:
    text = f"{domain.title} {domain.purpose}".lower()
    return any(phrase in text for phrase in FORBIDDEN_DIAGNOSTIC_PHRASES)
